spring.application.name=quizApp


spring.datasource.url = jdbc:mysql://localhost:3306/QuizApp
spring.datasource.username = root
spring.datasource.password = Zeeshan@135
spring.jpa.hibernate.ddl-auto=update